# 개발 환경 셋팅
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  # Redis 설정
  redis:
    host: localhost
    port: 6379
    password:


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  error:
    include-stacktrace: always
    include-message: always